# Generated by Django 4.1.5 on 2023-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "contribution",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("Title", models.CharField(blank=True, max_length=250, null=True)),
                ("type", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "Hand_out_date",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "hand_in_date",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
