# Generated by Django 4.1.7 on 2023-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_weeklytodolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetask',
            name='taskpriority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Medium Priority', 'Medium Priority'), ('Low Priority', 'Low Priority')], default='Medium Priority', max_length=20),
        ),
        migrations.DeleteModel(
            name='WeeklyTodoList',
        ),
    ]
