# Generated by Django 4.1.7 on 2023-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_thetask_suggesteddeadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thetask',
            name='suggesteddeadline',
        ),
        migrations.AddField(
            model_name='assessment',
            name='suggesteddeadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
